- src/pages/index.astro
Sugerencias de cambios directos al texto y orden de los elementos en `index.astro`
Hay una clase que creó @anattolia para comentar cosas de las que no está segura y se ven en otro color en la página. Se llama 'comentarios'. Sugiero que revisemos eso para introducir y revisar los comentarios editoriales de cosas que hay que definir entre varios.
Hice un .pdf con comentarios de ese tipo y creo que si bien limpiar el código puede ser tedioso, es más fácil aplicarlos con la clase `comentarios` y que lo notemos en una primera pasada, que ir Issue por Issue tratando de revisar cosas relativamente pequeñas. Para que lo pensemos en la junta. Si no va, pues, definir cómo se procede con los Issues para ese tipo de cosas.
Dejé esos comentarios en el pdf a continuación y en el #7 
[VACS _ Imagina + …
> 🚧 Lectura erratas sugerencias

- src/componentes/Glosario.astro
- src/pages/index.astro
Pasar glosario a un componente independiente.
> 🧱componente Glosario

- src/componentes/Glosario.astro
- src/componentes/Menu.astro
- src/pages/index.astro
- src/plantillas/Plantilla.astro
- src/scss/estilosGlobales.scss
Agregar componente glosario como un elemento que abre y cierra.
> 📖 Glosario

- src/componentes/Glosario.astro
- src/componentes/Menu.astro
- src/pages/recursos.astro
Agregar página de Recursos con la bibliografía de cada paper.
> ➕ Agregar página Recursos

- src/componentes/Creditos.astro
- src/componentes/Desplegable.astro
- src/componentes/Glosario.astro
- src/componentes/Menu.astro
- src/plantillas/Plantilla.astro
Agregar componente Créditos que funciona como Glosario.
> ✨ Agregar componente Créditos

- src/componentes/Glosario.astro
- src/componentes/Mapa.astro
Corregir error de leyendas en mapa.
> 🐛 corregir error de mapa

- src/componentes/Desplegable.astro
- src/componentes/Glosario.astro
- src/scss/estilosGlobales.scss
Ajustes de estilo en `Glosario` con la nueva estructura de `Desplegable`
> 🐛 Ajustes glosario con la estructura desplegable

- src/pages/index.astro
- src/pages/proyecto1.astro
- src/pages/proyecto2.astro
- src/pages/proyecto3.astro
- src/scss/_diagramacion.scss
- src/scss/estilosGlobales.scss
Creé una clase `anchoTitulo` para diferenciarlo de `contenidoColumna` e hice un ajuste en el querie de corte4.
Moví un poco el margen superior
> 📏 avances tamaños queries columna

- src/componentes/graficas/proyecto2/Grafica1.astro
- src/datos/p2Aces.ts
- src/datos/p2ConductasRiesgo.ts
- src/pages/proyecto2.astro
> 📈 Agregar gráfica aces y datos a historia 2

- src/pages/proyecto2.astro
Agregar el cierre que mandó Julián a la historia 2 y limpiar código.
> ✨ Agregar cierre a historia 2

- astro.config.mjs
- package.json
- src/componentes/Colombina.astro
- src/componentes/PuntosPorcentuales.astro
- src/componentes/graficas/proyecto2/Grafica2.astro
- src/datos/p2ConductasRiesgo.ts
- src/pages/proyecto1.astro
- src/pages/proyecto2.astro
- src/plantillas/Plantilla.astro
- src/scss/estilosGlobales.scss
- yarn.lock
Agregar gráfica de puntos porcentuales y corregir textos de historia 2.
*Incluye rebase de main.
> 📈  Puntos porcentuales

- src/componentes/graficas/proyecto1/Grafica2.astro
- src/datos/migracionViolenciaPdet.ts
- src/pages/proyecto1.astro
Agregar gráfica y corregir textos en historia 1.
Faltan otras gráficas por confirmar con las autoras.
> Graficas historia 1

- src/scss/_diagramacion.scss
- src/scss/estilosGlobales.scss
Algunos expermientos en proceso. Sobre todo para ir avanzando
> 🤡 experimentos y ajustes

- src/pages/index.astro
- src/pages/proyecto1.astro
- src/scss/_diagramacion.scss
Estaban desacomodadas las columnas.
> 🐛Corrección de detalles de historia 1

- .prettierrc.json
- src/componentes/Colombina.astro
- src/componentes/Torta.astro
- src/componentes/graficas/proyecto1/Grafica1.astro
- src/componentes/graficas/proyecto3/Grafica1.astro
- src/componentes/graficas/proyecto3/Grafica2.astro
- src/componentes/graficas/proyecto3/Grafica3.astro
- src/datos/p3AgresionSexualConocidos.ts
- src/datos/p3AgresionSexualEdad.ts
- src/datos/p3ViolenciaPorGenero.ts
- src/pages/proyecto3.astro
Agregar algunas gráficar a la historia 3 y crear el componente `gráfica de torta`.
*Faltan otras gráficas pero para ir integrando.
> 📈  Graficas historia 3 Parte I

- src/componentes/Colombina.astro
- src/componentes/ColombinaComparacion.astro
- src/componentes/graficas/proyecto1/Grafica1.astro
- src/componentes/graficas/proyecto1/Grafica2.astro
- src/componentes/graficas/proyecto1/Grafica3ViolenciaFisica.astro
- src/componentes/graficas/proyecto1/Grafica4ViolenciaEmocional.astro
- src/componentes/graficas/proyecto1/Grafica5ViolenciaSexual.astro
- src/componentes/graficas/proyecto1/Grafica6SaludMentalPdet.astro
- src/componentes/graficas/proyecto1/Grafica7SaludMentalGenero.astro
- src/datos/p1SaludMentalGenero.ts
- src/datos/p1SaludMentalPdetNoPdet.ts
- src/datos/p1ViolenciaEmocionalGenero.ts
- src/datos/p1ViolenciaFisicaPdetNoPdet.ts
- src/datos/p1ViolenciaSexualGenero.ts
- src/pages/proyecto1.astro
> Colombinas comparadas

- src/componentes/Personitas.astro
- src/componentes/graficas/proyecto3/Grafica1.astro
- src/componentes/graficas/proyecto3/Grafica2.astro
- src/componentes/graficas/proyecto3/Grafica3.astro
- src/componentes/graficas/proyecto3/Grafica4AgresorFisico.astro
- src/datos/p3AgresionSexualConocidos.ts
- src/datos/p3AgresionSexualEdad.ts
- src/datos/p3ViolenciaFisicaAgresor.ts
- src/datos/p3ViolenciaPorGenero.ts
- src/pages/proyecto3.astro
Agregar gráficas a historia 3 y corregir detalles de gráficas.
> 🌟 Avances en historia 3

- src/pages/index.astro
- src/scss/estilosGlobales.scss
Ajustes sobre todo en el índex: enlaces a historias y alguno espacios
> 👧🏽 ajustes de diseño 29 y 30 de agosto

- src/pages/recursos.astro
Ajustes de estilo y correcciones en el marcaje de título en la bibliografía
> 👷 ajustes en *Recursos*

- src/componentes/Glosario.astro
- src/componentes/Indice.astro
- src/pages/index.astro
- src/pages/proyecto1.astro
- src/pages/proyecto2.astro
- src/pages/proyecto3.astro
- src/pages/proyecto4.astro
- src/scss/estilosGlobales.scss
- src/utilidades/constantes.ts
avances editoriales en index y glosario, y uno pequeño en el proyecto 4
> 🐛 avances editoriales

- src/componentes/Creditos.astro
- src/componentes/Desplegable.astro
- src/componentes/Glosario.astro
- src/scss/estilosGlobales.scss
avances en estilo de los créditos
> 🐛 avances en créditos

- src/componentes/Creditos.astro
- src/componentes/Desplegable.astro
- src/componentes/Glosario.astro
- src/componentes/graficas/proyecto1/Puntos.astro
- src/pages/index.astro
- src/pages/proyecto1.astro
- src/pages/proyecto3.astro
- src/pages/proyecto4.astro
Ajustes de contenido en proyectos 1, 3 y 4
Ajustes en glosario. (@1cgonza solucionó el #101 )
Carga de información en créditos.
Ajustes en el index (solucionado #103 )
> 🚀 Ajustes 1,3,4, glosario.creditos.desple.index.

- src/pages/proyecto1.astro
- src/pages/proyecto3.astro
Comentar gráficas de las que no hay datos para que no se vean.
> 🔥 Quitar gráficas de las que no hay datos

- src/componentes/Creditos.astro
- src/componentes/Glosario.astro
- src/pages/index.astro
- src/pages/proyecto1.astro
- src/pages/proyecto2.astro
Correciones editoriales en los proyectos 1, 2, 3 y 4, glosario y crédtios listas. 
:)
Dejé comentadas muchas cosas porque fue mucho trabajo de marcaje de @anattolia  y quiero tenerlas un tiempo por si se arrepienten de algo en esa lectura ya lista
> ⚡️ correción editorial 1, 2, 3, 4 lista.

- src/componentes/Indice.astro
- src/scss/estilosGlobales.scss
Corregir error en el enlace de índice de historia 4 y margen en pantallas grandes.
> 🐛 Corregir error en índice

- src/componentes/Desplegable.astro
- src/componentes/Encuesta.astro
- src/componentes/Menu.astro
- src/componentes/Personitas.astro
- src/pages/index.astro
- src/pages/proyecto2.astro
- src/plantillas/Plantilla.astro
- src/scss/estilosGlobales.scss
Agregar componente `encuesta` y ponerla en el menú para que abra como desplegable.
> 📝 Agregar encuesta

- src/componentes/Indice.astro
- src/componentes/Menu.astro
- src/pages/index.astro
- src/pages/proyecto4.astro
- src/scss/estilosGlobales.scss
Limpiar código html de historia 4 y borrar código comentado de css.
> 🔥 Limpiar código html y css

- src/pages/recursos.astro
adelantos en la bibliografía del paper de Stigma, que está larguísima
> 😰 adelantos en la bibliografía

- src/pages/recursos.astro
por fin cargué los 100 y pucho referentes del paper de revisión
> 🍱  fin de la bibliografía eterna
